baseurl = "nelari.us/"
languageCode = "en-us"
title = "My stuff"

[Params]
  author = "Johann Muszynski"

  title = "asdf"
  subtitle = "where science and software collide"

  # You can choose between green, orange, red and blue.
  themeColor = "blue"
  # Enable Google Analytics be inserting your tracking code
  googleAnalytics = ""

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name = "Johann Muszynski"
  bio = "I work as a junior programmer at [Umbra](http://umbra3d.com/). I have a Master's degree in theoretical physics."
  description = "This is where I write about stuff that I've been working on."
  location = "Helsinki, Finland" # optional
  github = "Nelarius" # optional

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs. 
  comments = "disqus"

  # Customize or translate the strings
  keepReadingStr = "Read more"
  backtotopStr = "Back to top"
  shareStr = "Share"
  pageNotFoundTitle = "404 - Page not found"